AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  FrontendDeployBucketDomainName:
    Type: String
  TranslateLambdaDomainName:
    Type: String

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: FrontendDeployBucket
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: FrontendDeployBucketOriginId
          ViewerProtocolPolicy: allow-all
          DefaultTTL: 86400
          MaxTTL: 31536000
          ForwardedValues:
            QueryString: true
        Enabled: true
        DefaultRootObject: /browser/index.html
        IPV6Enabled: true

          # Compress: true

        Origins:
          - DomainName: FrontendDeployBucketDomainName
            Id: FrontendDeployBucketOriginId
            OriginShield:
              Enabled: true
              OriginShieldRegion: us-east-1
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
          - DomainName: juzzzlncxnn2onelvr3cin22zm0qatmk.lambda-url.us-east-1.on.aws #FIXME replace with lambda
            Id: TranslateFunction
            OriginShield:
              Enabled: true
              OriginShieldRegion: us-east-1
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        
        CacheBehaviors:
          - PathPattern: /translate
            TargetOriginId: TranslateFunction
            ViewerProtocolPolicy: allow-all
            ResponseHeadersPolicyId: e61eb60c-9c35-4d20-a928-2b84e02af89c #Simple CORS AWS-Managed Policy
            ForwardedValues:
              QueryString: true
          
Outputs:
  CloudFrontDistribution:
    Description: CloudFront distribution
    Value: !GetAtt CloudFrontDistribution.DomainName
  
