AWSTemplateFormatVersion: "2010-09-09"

Resources:
  FrontendDeployBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        { "IndexDocument": "index.html", "ErrorDocument": "error.html" }

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendDeployBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: s3:GetObject
            Principal:
              Service: "*"
            Effect: Allow
            Resource: !Sub ${FrontendDeployBucket.Arn}/*