AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  translate-function

  Sample SAM Template for translate-function

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
Resources:
  TranslateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: translate/
      Role: !GetAtt TranslateFunctionRole.arn
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Translate:
          Type: Api
          Properties:
            Path: /translate
            Method: get

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: true

  TranslateFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        -
          PolicyName: S3Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Sid: AllowLogging
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
        -
          PolicyName: AwsTranslateReadOnly
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Action:
              - translate:TranslateText
              - translate:TranslateDocument
              - translate:GetTerminology
              - translate:ListTerminologies
              - translate:ListTextTranslationJobs
              - translate:DescribeTextTranslationJob
              - translate:GetParallelData
              - translate:ListParallelData
              - comprehend:DetectDominantLanguage
              - cloudwatch:GetMetricStatistics
              - cloudwatch:ListMetrics
              Resource: "*"

Outputs:
  TranslateApi:
    Description: API Gateway endpoint URL for Prod stage for Translate function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/translate/"
  TranslateFunction:
    Description: Translate Lambda Function ARN
    Value: !GetAtt TranslateFunction.Arn
  TranslateFunctionIamRole:
    Description: Implicit IAM Role created for Translate function
    Value: !GetAtt TranslateFunctionRole.Arn
