AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  translate-function

  Sample SAM Template for translate-function

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
Resources:
  TranslateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: translate/
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      Role: arn:aws:iam::701806000562:role/InitialTranslateStack-TranslateFunctionRole-mbBcRkWh9HnT #Change to reflect your lambda role from the main stack
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Translate:
          Type: Api
          Properties:
            Path: /translate
            Method: get

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: true

Outputs:
  TranslateFunctionUrl:
    Description: Function URL for Prod stage for Translate function
    Value: !GetAtt TranslateFunctionUrl.FunctionUrl
  TranslateFunction:
    Description: Translate Lambda Function ARN
    Value: !GetAtt TranslateFunction.Arn
