on:
    push:
      branches:
        - main

env:
    AWS_REGION : "us-east-1" #Change to reflect your Region
 
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: aws-actions/setup-sam@v1
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::701806000562:role/GitHubActions-AssumeRoleWithAction #change to reflect your IAM role’s ARN
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
        # sam build 
    - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --s3-bucket asdf-frontenddeploybucket-zvg1rao9r1a8 --capabilities CAPABILITY_IAM --region ${{ env.AWS_REGION }} 
  